import { fuzzyFindAny } from "../fuzzy.js";
import { makeFinding } from "../helpers.js";
import type { Rule } from "../types.js";

const PHRASES = [
  "delve into",
  "dive into",
  "navigate the landscape",
  "navigate the complexities",
  "navigate the intricacies",
  "navigating complex ecosystems",
  "embark on a journey",
  "rich tapestry",
  "vibrant tapestry",
  "tapestry of",
  "in the realm of",
  "stands as a testament",
  "a testament to",
  "is a testament to",
  "serves as a testament",
  "plays a crucial role",
  "plays a pivotal role",
  "plays a vital role",
  "plays a key role",
  "in todays fast paced world",
  "in todays digital age",
  "in todays digital landscape",
  "in this fast paced digital",
  "in the ever evolving landscape",
  "ever evolving",
  "ever changing",
  "at the heart of",
  "in the heart of",
  "the world of",
  "in the world of",
  "treasure trove",
  "intricate dance",
  "intricate web",
  "intricate tapestry",
  "multifaceted",
  "look no further",
  "paramount importance",
  "pivotal moment",
  "key turning point",
  "load bearing",
  "valuable insights",
  "gain valuable insights",
  "deeply rooted",
  "indelible mark",
  "setting the stage",
  "diverse array",
  "imagine a world",
  "at its core",
  "in essence",
  "buckle up",
  "thats only half the story",
  "heres the kicker",
  "heres the truth",
  "real talk",
  "the truth is",
  "underscoring its",
  "underscores its",
  "highlights its",
  "reflects broader",
  "a beacon of",
  "a symphony of",
];

export const rule: Rule = {
  id: "ai-tell-phrasebank",
  name: "AI-tell phrasebank",
  severity: "error",
  description:
    "Phrases that overwhelmingly indicate AI-generated prose. Replace with concrete, specific language.",
  phrases: PHRASES,
  check(ctx) {
    return fuzzyFindAny(ctx.prose, ctx.tokens, PHRASES, { allowInserts: 1 }).map((m) =>
      makeFinding(
        ctx,
        m.start,
        m.end,
        `AI phrasebank match: "${m.text}" (≈ "${m.phrase}"). Rewrite with concrete specifics.`,
      ),
    );
  },
};
